### PR TITLE
Permit prototype inspection

### LINKED ISSUE #43: Useful view of instances of classes
A better view of a class instance that makes discoverability of its methods easier. The current best way is to use autocomplete (`s.<Tab>`), but I don't think many people know to reach for that.

Current view of a class:
image

Prototype pointer in Chrome's debugger view:
image

Prototype pointer in Safari's debugger view:
image

### PR DESCRIPTION
**Pull request by tmcw**
Fixes #43 by allowing one to browse through prototype chains and the non-enumerable prototype methods and properties. Nifty for FileAttachment and DatabaseConnector.

### CODE REVIEW

**Comment by visnup** [comment]
Never mind about that [convention](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto) I guess:

> Deprecated
> This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

**Comment by tmcw** [comment]
> Also, is there an intended sorting for a prototype's properties?

Object.getOwnPropertyDescriptors uses the same 'iteration order' of objects (that is now specified in the spec) as Object.keys() or `for in` iteration.

I'll peruse the different ways to name the prototype - we could also use fancier formatting for it, like Safari does.

**Comment by tmcw** [comment]
The world of options: https://www.are.na/tom-macwright/formatting-prototypes-in-inspectors

- RunKit & Safari: `[Uint8Array Prototype]` (styled with CSS)
- Chrome: `__proto__: TypedArray`
- Firefox: `<prototype> Uint8ArrayPrototype`

**Comment by visnup** [comment]
Interesting that none of them went with `[Uint8Array.prototype]` which hints at the real syntax to access it.

**Pull request merged**
